version: "3.8"

services:
  mongodb:
    image: mongo:5.0.2
    container_name: mongodb
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    networks:
      - app-network
    volumes:
      - db:/data/db
    
  appservice:
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - PORT=$NODE_LOCAL_PORT
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - JWT_SECRET_KEY=$JWT_SECRET_KEY 
      - TOKEN_HEADER_KEY=$TOKEN_HEADER_KEY
    networks:
      - app-network
    stdin_open: true
    tty: true

networks:
  app-network:
volumes:
  db:
    